"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.createStorageBucket = exports.createVoteCollection = exports.createCommentCollection = exports.createAnswerCollection = exports.createQuestionCollection = void 0;
const question_collection_1 = require("./server/question.collection");
exports.createQuestionCollection = question_collection_1.default;
const answer_collection_1 = require("./server/answer.collection");
exports.createAnswerCollection = answer_collection_1.default;
const comment_collection_1 = require("./server/comment.collection");
exports.createCommentCollection = comment_collection_1.default;
const vote_collection_1 = require("./server/vote.collection");
exports.createVoteCollection = vote_collection_1.default;
const storagesetup_1 = require("./server/storagesetup");
exports.createStorageBucket = storagesetup_1.default;
